### ISSUE TITLE
Incremental Backup does not work; Archive attribute is never cleared

### ISSUE THREAD

**Issue by st-anton** [Isiweb/7zBackup#10]
A full backup is working properly, all included / excluded pathes and files works. But incremental backup do not work as the Archive attribute is never touched. I tested, whether the Archive attribute is used at all: If I clear the attribute manually, the file is not put in the zip, this does work properly.
The problem seems to be somewhere in 7zBackups.ps1 line 876ff. Example with 3 files to backup and a forth to omit due to a cleared Archive attribute. 
[Debug.txt](https://github.com/Isiweb/7zBackup/files/1763795/Debug.txt)
The $ArchivedItemsCount is 6 (?), The first two files are the include and exclude list, the last one is the selection info. Unexceptingly so far. Buth none of the files Archive atrribute is cleared, neither in c:\~9db3\... not in the original folder.

**Comment by AndreaLanfranchi** [comment]
Could you please post the full command line you use to perform your icremental ?

**Comment by st-anton** [comment]
Here it comes:
.\7zBackup.ps1 --type incr --selection D:\temp\testbak\7zBackup-master\7zBackup.selection.txt --destpath D:\temp\testbak\bak

**Comment by AndreaLanfranchi** [comment]
Are your "uncleared" files zero sized ?
If that is the case then Issue #4 applies.
Try changing archive type from 7z to zip and please report.

**Comment by st-anton** [comment]
The files are normal pdf files with some page of contents (200 to 400kByte).
I updated 7z.msi to latest version 18.01 and repeated with zip instead of 7z format. The zip files (both full and incr) are a little bit bigger than the 7z, but that's clear. But there is no change in the behaviour. Still the attribute is unchanged.
![file_attribute](https://user-images.githubusercontent.com/2517417/36782705-0995af90-1c7a-11e8-9d19-1d6454d20c59.png)

**Comment by AndreaLanfranchi** [comment]
Hmmm .... that's getting tricky.
I've set-up a similar environment and I get the Archive attribute properly cleared.
Could you please report : 

1. The credentials scope 7zbackup.ps1 is ran with
2. The security details of any among the "uncleared" files 

Thanks

**Comment by st-anton** [comment]
Thanks for your answer, sorry for the delay.
What do you mean by credentials scope? I'm not familiar with Powershell / Script, but some knowledge of php helped me to look into the script. So how can I answer your question? I'm running Powershell as Administrator (ctrl shft PowerShell, click away the 'allow the app...'), got to the path where 7zbackup is and start the script. By the way: I was aware, that I use the Powershell version that comes with Windows: C:\Windows\System32\WindowsPowerShell\**v1.0**\powershell.exe  May there be a problem? I read about a version 6 already existing and dowloaded from git. This aborts with an error: 'Can't write into . Check permission'. 
What version do you use?

**Comment by AndreaLanfranchi** [comment]
To check which version of PowerShell you're on open a PS shell and run Get-Host

This is mine 

```
PS C:\WINDOWS\system32> get-host

Name             : ConsoleHost
Version          : 5.1.16299.248
InstanceId       : 199b74d5-fe33-44dc-9b95-c97a685d430d
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : it-IT
CurrentUICulture : it-IT
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

PS C:\WINDOWS\system32>

```

**Comment by AndreaLanfranchi** [comment]
Any news ?

**Comment by st-anton** [comment]
confusing. The path name says 1.0, but get-host says it is 5.1.16299.248 . In fact, it is exactly the version you have, exept I have the german one.
Step by step:
Windows + X -> Windows PowerShell (Administrator)
Accept  'allow the app...'
Change the directory to c:\temp\testbak\7zBackup-master
type in  .\7zBackup.ps1 --type full --selection C:\temp\testbak\7zBackup-master\7zBackup.selection.txt --destpath C:\temp\testbak\bak
Please find the complete test environment in the zip: 
I zipped after doing the backup, but still the archive attribute is set.
[testbak.zip](https://github.com/Isiweb/7zBackup/files/1798366/testbak.zip)

**Comment by AndreaLanfranchi** [comment]
Sorry for being late.
Please do a test for me.
Modify the script roughly at line 884 and replace

`$item = ( $item | Set-ItemProperty -Name Attributes -Value ($_.Attributes -bXOR $archiveAttr) -Force -PassThru )
`
with 

`$item = Set-ItemProperty -Path $item.FullName -Name Attributes -Value ($item.Attributes -bXOR $archiveAttr) -Force -PassThru
`

Please report

**Comment by st-anton** [comment]
That's it! It does work as expected!
Thanks a lot.
Anton
