### ISSUE TITLE
error: You do not have sufficient privilege to perform this operation 

### ISSUE THREAD

**Issue by max-ant** [Isiweb/7zBackup#11]
Windows 10, During execution 
`cmd /c MKLINK /D  C:\~b229\tempalias, c:\temp\test`
I got 
```
You do not have sufficient privilege to perform this operation.
   Failed to create Symbolic Link [tempalias] to [c:\temp\test]

```
Does you script require administrator privileges to run?
If yes - I think this is not good. And this is not documented in wiki.

**Comment by AndreaLanfranchi** [comment]
Hi and thank you for dropping in.

Admin privileges are not endorsed by the script but by the underlaying file system.
In Windows 10 all operations on the root of the system drive require Admin privileges.
On the other hand if you have a secondary partition (eg. D) which is NTFS you can execute the script with --workdrive switch added 

`.\7zbackup.ps1 --workdrive D <yourotherswitches>`

But there is a secondary aspect to keep in mind: the script (on certain circumstances) lowers the Archive bit on processed files thus it is mandatory that the user credentials used to run the script do have write permissions on each file to backup.

**Comment by max-ant** [comment]
As I see In Windows 10, any call to MKLINK require privileges.
Even when you have permission to write on D: you will have error.

**Comment by AndreaLanfranchi** [comment]
The behavior is set by group policy.
Run gpedit.msc
Navigate to Computer configuration → Windows Settings → Security Settings → Local Policies → User Rights Assignment → Create symbolic links
Here you can set which users can create symbolic links.

**Comment by urwa8023** [comment]
[Avast Premier License Key](https://crackthunder.com/avast-premier-license-key/) is the complete antivirus protection program that prevent your computer against the malware content. It provides protection against the hacking of the computer. Furthermore, It has easy to use interface that helps you understand the software.
