### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by marcomangiante** [Isiweb/7zBackup#5]
Hello,

at the end of the process I have the message "Done with : 1 warnings, Check logs!": where to find the logs? I also have tried the script on a particular directory and the process exit with the message "Cancelled ! 7-Zip reported a fatal error.": is it possible to have a log why 7-Zip exit with this?
For the second error, I suppose there is on the directories some type of lock from a software (Zucchetti) on them.

**Comment by AndreaLanfranchi** [comment]
@marcomangiante 
which version of the script are you on ?
Could you please install latest ? It shows some additional infos if any.

However there are two cases where logs may be missing:
* 7zip encounters a locked file
* 7zip finds the target unit of backup to be full

**Comment by AndreaLanfranchi** [comment]
Also ... regarding "Done with : 1 warnings, Check logs!"

Warnings are reported in the body of the message.

**Comment by marcomangiante** [comment]
Hello,

I tried with downloading the latest version but at the end of the process I obtain the error reported previously. I also tried to stop the service (Zucchetti ACUConnect) that I supposed to lock the directory to backup but without success. It seems that the issue is during the zip of the files? I also verified that the target path of the backup is not full; is it possible to redirect the information in a log to see what happens?

**Comment by AndreaLanfranchi** [comment]
Hi Marco,
script (since release 2.0.6) already captures every output from 7Zip sent to stderr.
These messages are printed out by the script just after the summary of files to be backupped.
To give you an example 

```
                                  ----------- ----------------- 
 Total                                 5.579         43.775,68
                                  =========== ================= 
 Performance average                  14.390  files per minute
                                  =========== ================= 
 
HERE BEGIN THE STDERR OUTPUT FROM 7ZIP

 ! Sole.24\sole.24\VLGC6_ACC\dati\VLGC-FAO.ldb WARNING: The system cannot find the file specified. Sole.24\sole.24\VLGC6_ACC\dati\VLGCMAIN.ldb WARNING: The system cannot find the file specified.

HERE ENDS THE STDERR OUTPUT FROM 7ZIP 

 Created SERVER01-incr-20171122-201011.7z in G:\Backup 
 Archive Size 21.658,89 MB = 49,48% of original size
 Completed in 0 days, 2 hours, 29 minutes, 29,407 seconds
 Perfomance 4,88 MB/Sec.
```

**Comment by marcomangiante** [comment]
Hello,

I have this instead:

                                 ----------- -----------------
Total                                 1.773            424,52
                                 =========== =================
Performance average                  13.264  files per minute
                                 =========== =================


Cancelled ! 7-Zip reported a fatal error.
NO VALID ARCHIVE HAS BEEN CREATED

Sorry for bad impagination.

**Comment by AndreaLanfranchi** [comment]
Ok I see ... 
This message is caught by the script when 7zip aborts abruptly it's execution due to a serious error.
This condition is recorded under exit code 2 
There is not much knowledge base about 7zip exiting with code 2 but Igor Pavlov (the author of 7zip) suggest to investigate on possible memory damage or network error.
Are you trying to save your backup on a remote share or NAS ?

Suggest to read here
https://sourceforge.net/p/sevenzip/discussion/45798/thread/6d124282/
https://sourceforge.net/p/sevenzip/discussion/45797/thread/d816f22f/

Sorry I can't help more but I do not control the code of 7zip.

**Comment by marcomangiante** [comment]
Hello,

I read the code and also a comment found on another site where there is suggested that there is much knowledge about this type of error.
I'm trying to save the backup simply on a volume on my server: maybe there is a problem with the volume (virtual disk on a virtual machine) even if I use it to save other directories with the script.

I try to read your suggested link and to do other try.

**Comment by marcomangiante** [comment]
The only thing that I noticed is this:

PS>TerminatingError(Out-File): "Cannot bind argument to parameter 'FilePath' because it is null."

PS>TerminatingError(New-Object): "Exception calling ".ctor" with "3" argument(s): "Empty path name is not legal.""

 Scanning ...
 ------------------------------------------------------------------------------

PS>TerminatingError(Get-ChildItem): "Cannot bind argument to parameter 'LiteralPath' because it is null."

**Comment by AndreaLanfranchi** [comment]
Well this should not happen.
Which OS are you on ? Which version of Powershell are you on ?

**Comment by marcomangiante** [comment]
Hello,

the OS is Windows Server 2012 R2 and the PowerShell version is 4.0; to see that errors I created a simple script with your inside:

```posh
$LogFile = "C:\Scripts\log_task.txt"
$destination = "E:\"
Start-Transcript -path $LogFile -append
Set-ExecutionPolicy Bypass
Esecuzione dello script completo
.\7zBackup.ps1 --type full --selection test_selection.txt --destpath $destination
Stop-Transcript

**Comment by AndreaLanfranchi** [comment]
Frankly I do not understand why you should wrap the launch of 7zbackup.ps1 inside a transcript block (which may cause problems as it redirects stdout of a script which also redirects stdout of 7zip)
All you need to watch is printed on screen or, if you want, sent by email.

Simply launch the script in interactive mode 

`.\7zBackup.ps1 --type full --selection test_selection.txt --destpath E:\`

and report the output.

**Comment by marcomangiante** [comment]
Andrea, I used a transcript only because I have no output for 7-zip fatal error and try to see if there was other messages available.

**Comment by marcomangiante** [comment]
Finally resolved the issue: Zucchetti has 2 services (and not 1 as I supposed previously) that locked the files and I found it thanks to SysInternal Process Explorer; now I have no more fatal error from 7-zip.

**Comment by AndreaLanfranchi** [comment]
Glad to hear it.
Check out new relases and feel free to suggest new features.
