### ISSUE TITLE
A warning on rmdir usage in Powershell is required

### ISSUE THREAD

**Issue by alesscor** [Isiweb/7zBackup#6]
At removing symbolic links, it must be warned that the usage of `rmdir` must be of special care on Powershell as described on this SuperUser entry: https://superuser.com/a/595197/557791 . **If there is no care you will accidentally delete the symlink's source (that happens to my friend's friend's naive friend)**.

So I'd modify the current `README.md` file this way, at line 38:
```
* To remove a symbolic link use the RD command line. If you are using Powershell, be more careful and use `cmd /c rmdir .\thesymlink`.
```
And I'd modify the current `7zBackup.ps1` file this way, at line 811:
```
            New-Item (Join-Path -Path $BkRootDir -ChildPath "__README__PLEASE__README__.txt") -type File -value "This directory contains Symbolic Links.`nDO NOT DELETE THIS DIRECTORY AND IT'S CONTENTS USING WINDOWS EXPLORER.`nUse RD command delete symbolic links and then safely delete the directory, use cmd /c rmdir <thesymlink'sname> in case of using Powershell." | Out-Null
```

**Comment by AndreaLanfranchi** [comment]
Merged
