### ISSUE TITLE
Installation guide: Is Junction needed for Windows 10 (1709)?

### ISSUE THREAD

**Issue by st-anton** [Isiweb/7zBackup#9]
The installation guide says, Junction is not required if running Windows Vista / 7 / 2008. Obvious (7zBackup.ps1  line 2179) all newer Windows versions (Vista and newer) do not need Junction anymore. Isn't it? Can you please update the installation guide accordingly?

**Comment by AndreaLanfranchi** [comment]
For Windows Vista or better Junction is not needed as script uses native mklink from the OS.
This is already stated here
https://github.com/Isiweb/7zBackup/wiki/Requirements#junction-tool-skip-if-youre-on-windows-vista-or-better
